#  DataBase
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Spring Live Reload 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# mybatis mapper 경로 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 이미지 업로드 설정
file:
  upload-path: /Users/an-yeongjun/Desktop/project/image
  stored-path: file:///Users/an-yeongjun/Desktop/project/image/
  default-image: /images/userProfile.png
  allowed-extensions: jpg,jpeg,png