#  DataBase
spring:
  datasource:
    url: ENC(tumGKonMWXpO4uQUpAkUBTw6JWloKiI4Nsg/ArwT18vaPf1+kQBjSEVnNVG1RMjAAhboQdbhejTG3bEB685wV34sBOxncMkbuOkEmWtgKp9BOdSQCBw/KjamYPsT1JVqiSSD7KJqJvw=)
    username: ENC(V/TYpjWkapbPr7+fGEqQ6w==)
    password: ENC(Z+v9LsPI0C/pdRJGf+QS2Q==)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Spring Live Reload 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # Oauth2 설정(구글)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(p6AFP4L3TWgKgP6fBZiWr8jXAoTZOarZc335sn5rWDXUAAIVAbzftri/xnypSeUf1RLc6Cd2UDq0qGlJTfUiTcQjgtEcQ/RAL2W1fOyjr3W3G9J7CEBOXw==)
            client-secret: ENC(zQmgrwNgMriLP7pVkN6nlFKlde+fSA2wfjO8Krks+IYjK3MBqBaWtpnZ5Vmgu2Be)
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope: profile

# mybatis mapper 경로 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 이미지 업로드 설정
file:
  upload-path: /Users/an-yeongjun/Desktop/project/image
  stored-path: file:///Users/an-yeongjun/Desktop/project/image/
  allowed-extensions: jpg,jpeg,png

# log4j2 설정
logging:
  level:
    jdbc.sqlonly: off
    jdbc.sqltiming: off
    jdbc.resultsettable: off
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.connection: off