#  DataBase
spring:
  datasource:
    url: jdbc:log4jdbc:mariadb://127.0.0.1:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  # Spring Live Reload 설정
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# mybatis mapper 경로 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 이미지 업로드 설정
file:
  upload-path: /Users/an-yeongjun/Desktop/project/image
  stored-path: file:///Users/an-yeongjun/Desktop/project/image/
  allowed-extensions: jpg,jpeg,png

# log4j2 설정
logging:
  level:
    jdbc.sqlonly: off
    jdbc.sqltiming: info
    jdbc.resultsettable: info
    jdbc.audit: off
    jdbc.resultset: off
    jdbc.connection: off